#!/bin/bash
make clean
#
#  buildable platforms of somewhat questionable support level
#make lilypad
#make pro8
#make pro16
#make pro20
#make atmega328_pro8
#make sanguino
#make mega1280
#make luminet
#make diecimila
#make bobuino
#make wildfirev2
#make atmega1284
#make atmega16
#make atmega32
#make atmega88
#make atmega168p

#
# The "big three" standard bootloaders.
# These need to be built AFTER the platforms, or they'll get renamed
#make atmega8
#make atmega168
#make atmega328


make atmega1284 AVR_FREQ=16000000L BAUD_RATE=115200 UART=0 LED=B0 LED_START_FLASHES=2 -BIGBOOT
make atmega644p AVR_FREQ=16000000L BAUD_RATE=115200 UART=0 LED=B0 LED_START_FLASHES=2 -BIGBOOT
make atmega324 AVR_FREQ=16000000L BAUD_RATE=115200 UART=0 LED=B0 LED_START_FLASHES=2
make atmega164 AVR_FREQ=16000000L BAUD_RATE=115200 UART=0 LED=B0 LED_START_FLASHES=2
make atmega32 AVR_FREQ=16000000L BAUD_RATE=115200 UART=0 LED=B0 LED_START_FLASHES=2
make atmega16 AVR_FREQ=16000000L BAUD_RATE=115200 UART=0 LED=B0 LED_START_FLASHES=2
make atmega8535 AVR_FREQ=16000000L BAUD_RATE=115200 UART=0 LED=B0 LED_START_FLASHES=2